#################################### common config : ####################################
server:
  port: 8080
spring:
  application:
    name: train
  #Redis依赖
  # Redis服务器地址
  redis:
    host: 127.0.0.1
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 12345678
    # 连接超时时间（毫秒）
    timeout: 1000
    lettuce:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 10
        ## 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    #PostgreSQL配置
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 5
    minIdle: 5
    # 最大连接池数量
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  elasticsearch:
    rest:
      uris: 111.229.157.173:9200



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.psq.train.mysql